name: Regression Tests

on: [push, pull_request]

jobs:
  build:
    name: Running regression
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
      python-version: 3.9

    - name: Install Docker
      run: |
        sudo apt update
        sudo apt install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        sudo apt update
        apt-cache policy docker-ce
        sudo apt update
        sudo apt install docker-ce

    - name: Setup Verilator
      run: |
        alias verilator='sudo docker run -ti -v ${PWD}:/work --user $(id -u):$(id -g) verilator/verilator:latest ${@:1}'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox
      run: tox -- --splits 10
