name: Regression Tests

on: [push, pull_request]

jobs:
  build:
    name: Python ${{ matrix.python-version }} (${{ matrix.group }}/10)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]
        group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Verilator
      run: |
        sudo apt install -y --no-install-recommends verilator
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox -- --splits 10 --group ${{ matrix.group }}
