name: Regression Tests

on: [push, pull_request]

jobs:
  build:
    name: Running regression
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Verilator
      run: |
        sudo apt install -y --no-install-recommends make g++ perl python3 autoconf flex bison libfl2 libfl-dev zlibc zlib1g zlib1g-dev
        git clone https://github.com/verilator/verilator.git
        cd verilator
        autoconf
        ./configure
        make -j $(nproc)
        sudo make install

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox
      run: tox -- --splits 10
